App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.blog_list, name="blog_list")
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'


urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('signin', views.login_page, name='signin'),
]

My_Blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=200, verbose_name='Put a tutle')
    slug = models.SlugField(max_length=200, unique=True)
    blog_content = models.TextField(verbose_name='What is in your mind?')
    blogimage = models.ImageField(upload_to='blog_images')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.blog_title
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

App_Blog/views.py
from django.shortcuts import render

# Create your views here.
def blog_list(request):
    return render (request, 'App_Blog/blog_list.html', context={})

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
def signup(request):
    form = UserCreationForm()
    registered = False
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    
    dict = {'form':form, 'registered': registered}
    return render (request, 'App_Login/signup.html', context=dict)
    

def login_page(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
    return render (request, 'App_Login/login.html', context={'form':form})

My_Blog_project/views.py
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse



def index(request):
    return HttpResponseRedirect(reverse('App_Blog:blog_list'))

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}


{% block body_block %}

<h1> I am a blog list </h1>
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Login Page {% endblock %}

{% block body_block %}

<h2> Login your Account </h2>

<form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Login</button>

</form>

{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create new account {% endblock %}


{% block body_block %}
{% if registered %}
<div class="alert alert-success">
    Account created successfully <a href="{% url 'App_Login:signin' %}">login here</a>
</div>
{% else %}

<h2> Create new account </h2>
<form method="post">
    {% csrf_token %}
    {{ form | crispy }}

    {% csrf_token %}

    
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>

<p>Already have an account <a href="{% url 'App_Login:signin' %}">Login here</a></p>
{% endif %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>
      {% block title %}
        Blog Page
      {% endblock %}
    </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>



        <li class="nav-item active">
          <a class="nav-link" href="{% url 'App_Login:signup' %}">  sign up  </a>


        </li>

      </ul>
    </nav>
    <div class="container" style="padding-top: 20px">
      {% block body_block %}

      {% endblock %}

    </div>
    


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>